services:
  postgres:
    image: postgres:14.1
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-secret}
      POSTGRES_DB: ${DATABASE_NAME:-aiqfome}
      TZ: 'GMT-3'
      PGTZ: 'GMT-3'

    ports:
      - 5432:5432

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      timeout: 30s
      interval: 10s
      retries: 5
      start_period: 5s

    networks:
      - db-net

  zipkin:
    image: openzipkin/zipkin
    container_name: otel
    ports:
      - 9411:9411
    networks:
      - otel-net

networks:
  db-net:
  otel-net:
