// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/uesleicarvalhoo/aiqfome/internal/app/auth/dto"
)

// AuthorizeUseCase is an autogenerated mock type for the AuthorizeUseCase type
type AuthorizeUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, params
func (_m *AuthorizeUseCase) Execute(ctx context.Context, params dto.AuthorizeParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.AuthorizeParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthorizeUseCase creates a new instance of AuthorizeUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizeUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizeUseCase {
	mock := &AuthorizeUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
