// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/uesleicarvalhoo/aiqfome/internal/app/client/dto"
)

// DeleteClientUseCase is an autogenerated mock type for the DeleteClientUseCase type
type DeleteClientUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, p
func (_m *DeleteClientUseCase) Execute(ctx context.Context, p dto.DeleteClientParams) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.DeleteClientParams) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeleteClientUseCase creates a new instance of DeleteClientUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeleteClientUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeleteClientUseCase {
	mock := &DeleteClientUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
