// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	dto "github.com/uesleicarvalhoo/aiqfome/internal/app/client/dto"
)

// UpdateClientUseCase is an autogenerated mock type for the UpdateClientUseCase type
type UpdateClientUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, p
func (_m *UpdateClientUseCase) Execute(ctx context.Context, p dto.UpdateClientParams) (dto.Client, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateClientParams) (dto.Client, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.UpdateClientParams) dto.Client); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(dto.Client)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.UpdateClientParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUpdateClientUseCase creates a new instance of UpdateClientUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateClientUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateClientUseCase {
	mock := &UpdateClientUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
