// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/uesleicarvalhoo/aiqfome/internal/app/favorites/dto"

	mock "github.com/stretchr/testify/mock"
)

// AddProductToFavoritesUseCase is an autogenerated mock type for the AddProductToFavoritesUseCase type
type AddProductToFavoritesUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, p
func (_m *AddProductToFavoritesUseCase) Execute(ctx context.Context, p dto.AddProductToFavoritesParams) (dto.ProductFavorite, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.ProductFavorite
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.AddProductToFavoritesParams) (dto.ProductFavorite, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.AddProductToFavoritesParams) dto.ProductFavorite); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(dto.ProductFavorite)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.AddProductToFavoritesParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAddProductToFavoritesUseCase creates a new instance of AddProductToFavoritesUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAddProductToFavoritesUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AddProductToFavoritesUseCase {
	mock := &AddProductToFavoritesUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
