// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/uesleicarvalhoo/aiqfome/internal/app/favorites/dto"

	mock "github.com/stretchr/testify/mock"
)

// GetClientFavoritesUseCase is an autogenerated mock type for the GetClientFavoritesUseCase type
type GetClientFavoritesUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, p
func (_m *GetClientFavoritesUseCase) Execute(ctx context.Context, p dto.GetClientFavoritesParams) (dto.ClientFavorites, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 dto.ClientFavorites
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetClientFavoritesParams) (dto.ClientFavorites, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.GetClientFavoritesParams) dto.ClientFavorites); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Get(0).(dto.ClientFavorites)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.GetClientFavoritesParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGetClientFavoritesUseCase creates a new instance of GetClientFavoritesUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGetClientFavoritesUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *GetClientFavoritesUseCase {
	mock := &GetClientFavoritesUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
