// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/uesleicarvalhoo/aiqfome/internal/app/favorites/dto"

	mock "github.com/stretchr/testify/mock"
)

// RemoveProductFromFavoritesUseCase is an autogenerated mock type for the RemoveProductFromFavoritesUseCase type
type RemoveProductFromFavoritesUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, p
func (_m *RemoveProductFromFavoritesUseCase) Execute(ctx context.Context, p dto.RemoveProductFromFavoritesParams) error {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.RemoveProductFromFavoritesParams) error); ok {
		r0 = rf(ctx, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRemoveProductFromFavoritesUseCase creates a new instance of RemoveProductFromFavoritesUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRemoveProductFromFavoritesUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *RemoveProductFromFavoritesUseCase {
	mock := &RemoveProductFromFavoritesUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
