name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-lint:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install gocritic
        run: go install -v github.com/go-critic/go-critic/cmd/gocritic@latest

      - name: Run tests
        run: go test -covermode=atomic -count=1 -v ./... -short -race -coverprofile $(COVERAGE_OUTPUT) -json -ldflags=-extldflags=-Wl | gotestfmt
